OdeToFood/Models/CuisineType.cs
namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        German
    }
}

OdeToFood/Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        [Display(Name = "Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/ViewModels/HomeIndexViewModel.cs
using OdeToFood.Models;
using System.Collections.Generic;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

OdeToFood/ViewModels/RestaurantEditModel.cs
using OdeToFood.Models;
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.Controllers
{
    [Route("company/[controller]/[action]")]
    public class AboutController
    {

        public string Phone()
        {
            return "123412341241234";
        }
        
        public string Address()
        {
            return "masahosettes 2123";
        }
    }
}

OdeToFood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IRestaurantData _restautantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restautantData, IGreeter greeter)
        {
            _restautantData = restautantData;
            _greeter = greeter;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = new HomeIndexViewModel();
            model.Restaurants = _restautantData.GetAll();
            model.CurrentMessage = _greeter.GetMessageOfTheDay();

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _restautantData.Get(id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel model)
        {
            if (ModelState.IsValid)
            {
                var newRestaurant = new Restaurant();
                newRestaurant.Name = model.Name;
                newRestaurant.Cuisine = model.Cuisine;

                newRestaurant = _restautantData.Add(newRestaurant);

                return View("Details", newRestaurant);
            }
            else
            {
                return View();
            }
        }
    }
}

OdeToFood/Pages/Greeting.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;
        public string CurrentGreeting { get; set; }
        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public void OnGet(string name)
        {
            CurrentGreeting = $"{name}: { _greeter.GetMessageOfTheDay()}";
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);
            if (Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(Restaurant);
                return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
            }
            return Page();
        }

    }
}

OdeToFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();
            return View("Default", model);
        }

    }
}

OdeToFood/Pages/Greeting.cshtml
@page "{name}"

@model GreetingModel

<div>@Model.CurrentGreeting</div>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants

@model EditModel
@{
}


<h1>Edit @Model.Restaurant.Name</h1>


<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>
    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>
<div asp-validation-summary="All"></div>

OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>@RenderSection("footer", required: false)</footer>
</body>
</html>

OdeToFood/Views/Home/Create.cshtml
@using OdeToFood.Models
@model Restaurant


@{
    ViewBag.Title = "Create";
}

<h1>Create</h1>

<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>
<div asp-validation-summary="All"></div>

OdeToFood/Views/Home/Details.cshtml
@model Restaurant

@{
    ViewBag.Title = Model.Name;
}

<h1>
    @Model.Name
</h1>
<div>
    id: @Model.Id
</div>
<div>
    Cuisine: @Model.Cuisine
</div>
<a asp-action="Index" asp-controller="Home">
    Home
</a>

OdeToFood/Views/Home/Index.cshtml
@model OdeToFood.ViewModels.HomeIndexViewModel

@{
    ViewBag.Title = "Home Page";
}
<h1> All Restaurants!</h1>

@foreach (var restaurant in Model.Restaurants)
{
    @await Html.PartialAsync("_Summary", restaurant)
}

<div><a asp-action="Create">Add Restaurant</a></div>

OdeToFood/Views/Home/_Summary.cshtml
@model OdeToFood.Models.Restaurant
<section>
    <h3>@Model.Name</h3>
    <div>Cousine: @Model.Cuisine</div>
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model string
<div>@Model</div>

OdeToFood/Views/Shared/Components/LoginLayout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <div>Hello, @User.Identity.Name</div>
    <a class="btn btn-default" asp-controller="Account" asp-action="Logout">Logout</a>
}
else
{
    <a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>
}

OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OdeToFood</a>
            </div>
            <div class="navbar-right">
                <vc:logger></vc:logger>
            </div>
        </div>
    </nav>


    <div>
        @RenderBody()
    </div>
    <footer>@RenderSection("footer", required: false)</footer>
    @*@await Component.InvokeAsync("Greeter")*@
    <vc:greeter></vc:greeter>

    @*@if (User.Identity.IsAuthenticated)
        {
            foreach (var identity in User.Identities)
            {
                <h3>@identity.Name</h3>
                <ul>
                    @foreach (var claim in identity.Claims)
                    {
                        <li>@claim.Type  - @claim.Value</li>
                    }
                </ul>
            }
        }
        else
        {
            <div>You are anonymous!</div>
        }*@

</body>
</html>